openapi: "3.0.1"
info:
  version: "1.0.0"
  title: "Api sklep - produkty"
  
tags:
- name: "products"
  description: "Informacje o produktach"

paths:
  /api/order/user:
     get:
        tags:
        - "products"
        summary: "Zwraca wszystkie zamówienia aktualnie zalogowanego użytkownika"
        responses:
          "200":
            description: "Ok"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/OrderCollection"
          "404":
            description: "Not found"
  /api/order:
   post:
      tags:
      - "products"
      summary: "Dodaj zamówienie"
      parameters:
        - in: query
          name: products
          schema:
            $ref: "#/components/schemas/ProductIds"
      responses:
        "200":
          description: "Ok"
        "404":
          description: "Invalid status value"
components:
  schemas:
    Order:
      type: "object"
      properties:
        date:
          type: "string"
          format: "datetime"
          example: "2021-11-11 11:11:11"
        username:
          type: "string"
          example: "admin"
        products:
          type: "array"
          items:
            type: integer
          example: [1, 2, 3]
    ProductIds:
      type: "object"
      properties:
        products:
          type: "array"
          items:
            type: integer
          example: [1, 2, 3]
    OrderCollection:
      type: "object"
      properties:
        orders:
          $ref: "#/components/schemas/Order"
