openapi: "3.0.1"
info:
  version: "1.0.0"
  title: "Api sklep - produkty"
  
tags:
- name: "products"
  description: "Informacje o produktach"

paths:
  /api/product/all:
     get:
        tags:
        - "products"
        summary: "Zwróć wszystkie produkty"
        responses:
          "200":
            description: "Ok"
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/ProductCollection"
          "404":
            description: "Not found"
  /api/product/{id}:
   get:
      tags:
      - "products"
      summary: "Zwróć produkt o danym o id"
      parameters:
        - in: path
          name: id
          schema:
            type: "integer"
          required: true
      responses:
        "200":
          description: "Ok"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductFetch"
        "404":
          description: "Not found"
  /api/product:
   post:
      tags:
      - "products"
      summary: "Dodaj produkt"
      parameters:
        - in: query
          name: product
          schema:
            $ref: "#/components/schemas/ProductInsert"
      responses:
        "200":
          description: "Ok"
        "404":
          description: "Invalid status value"
components:
  schemas:
    ProductInsert:
      type: "object"
      required:
      - "id"
      - "name"
      - "price"
      - "categoryId"
      properties:
        id:
          type: "integer"
          format: "int64"
          example: 1
        name:
          type: "string"
          example: "Piwo żubr"
        price:
          type: "string"
          example: "2.20"
        categoryId:
          type: "integer"
          format: "int64"
          example: 1
    ProductFetch:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
          example: 1
        name:
          type: "string"
          example: "Piwo żubr"
        price:
          type: "string"
          example: "2.20"
        rating:
          type: "integer"
          format: "int64"
          example: 4
        stock:
          type: "integer"
          format: "int64"
          example: 43
        categoryId:
          type: "integer"
          format: "int64"
          example: 1
    ProductCollection:
      type: "array"
      items:
          $ref: "#/components/schemas/ProductFetch"
