security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        refresh:
            pattern: ^/api/auth/refresh-token
            stateless: true

        login:
            pattern: ^/api/auth
            stateless: true
            json_login:
                check_path: /api/auth/token
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        main:
            lazy: true
            provider: app_user_provider

    access_control:
        - { path: '^/api/product', method: POST, roles: IS_AUTHENTICATED_FULLY }
        - { path: '^/api/category', method: POST, roles: IS_AUTHENTICATED_FULLY }
        - { path: '^/api/user/get-login', method: POST, roles: IS_AUTHENTICATED_FULLY }
        - { path: '^/api/user/change-password', roles: IS_AUTHENTICATED_FULLY }
        - { path: '^/api/rate', method: POST, roles: IS_AUTHENTICATED_FULLY }
        - { path: '^/api/order', roles: IS_AUTHENTICATED_FULLY }
        - { path: '^/api/product', roles: PUBLIC_ACCESS }
        - { path: '^/api/category', roles: PUBLIC_ACCESS }
        - { path: '^/api/auth', roles: PUBLIC_ACCESS }

