get_product_collection:
    path: /api/products/get-product-collection
    controller: get_product_collection_action
    methods: [GET]
get_product:
    path: /api/products/get-product/{id}
    controller: get_product_action
    requirements:
        id: '\d+'
    methods: [GET]
put_product:
    path: /api/products/put-product
    controller: put_product_action
    methods: [POST]
generate_jwt_token:
    path: /api/auth/token
    methods: [POST]
gesdinet_jwt_refresh_token:
    path: /api/auth/refresh-token
    controller: gesdinet.jwtrefreshtoken::refresh
    methods: [POST]
register:
    path: /api/auth/register
    controller: App\Auth\Controller\RegistrationAction
    methods: [POST]