get_product_collection:
    path: /api/product/collection
    controller: App\Products\Controller\GetProductCollectionAction
    methods: [GET]
get_product:
    path: /api/product/{id}
    controller: App\Products\Controller\GetProductAction
    requirements:
        id: '\d+'
    methods: [GET]
post_product:
    path: /api/product
    controller: App\Products\Controller\PostProductAction
    methods: [POST]
generate_jwt_token:
    path: /api/auth/token
    methods: [POST]    
get_username:
    path: /api/user/get-login
    controller: App\Auth\Controller\LoginVerificationAction
    methods: [POST]
gesdinet_jwt_refresh_token:
    path: /api/auth/refresh-token
    controller: gesdinet.jwtrefreshtoken::refresh
    methods: [POST]
register:
    path: /api/auth/register
    controller: App\Auth\Controller\RegistrationAction
    methods: [POST]
get_single_category:
    path: /api/category/{id}
    controller: App\Categories\Controller\GetCategoryAction
    methods: [GET]
get_categories_list:
    path: /api/category/all/{visible}
    controller: App\Categories\Controller\GetCollectionCategoryAction
    methods: [GET]
post_category:
    path: /api/category
    controller: App\Categories\Controller\PostCategoryAction
    methods: [POST]
post_rating:
    path: /api/rate/{id}/{rating}
    controller: App\Rating\Controller\PostRatingAction
    methods: [POST]
update_stock:
    path: /api/stock/update/{productId}/{amount}
    controller: App\Stock\Controller\UpdateStockAction
    methods: [PATCH]
set_stock:
    path: /api/stock/set/{productId}/{amount}
    controller: App\Stock\Controller\SetStockAction
    methods: [PATCH]