get_product_collection:
    path: /api/products/get_product_collection
    controller: get_product_collection_action
    methods: [GET]
get_product:
    path: /api/products/get_product/{id}
    controller: get_product_action
    requirements:
        id: '\d+'
    methods: [GET]
put_product:
    path: /api/products/put_product
    controller: put_product_action
    methods: [PUT]
login:
    path: /api/login
    controller: login_controller::login
    methods: [POST]